feat(submission) Lambda service from collecting JSON from REST payloa…
cds-snc/covid-alert-server pull request #414
Opened 2021-01-15 05:40 UTC by tpjods

> simple micro-service to collect data in JSON format and save it as a unique object in to S3. This is a MVP solution that will accept any JSON file. The service will create a UUID for each new object.  close #407 Implement Microservices for collecting metrics.

This is a basic data collector. 

Requires 2 environment variables. 
"dataBucket"   <-- The name of the bucket you are saving to
"fileLoca" <-- The folder in the bucket you are saving to

It also requires an inline policy to be added to the lambda function providing putObject permissions on the bucket. If this is an encrypted bucket the KMS encrypt policy is also required.

2021-01-18 16:00 UTC, CalvinRodo requested changes
An automated test is also required for this piece of code, we use Jest as our JS Unit Testing Framework.

I took a look at your other PR you submitted I'm not seeing the issues there that are present here: https://github.com/cds-snc/covid-alert-server-qa-tools/pull/1

2021-01-18 16:29 UTC, wmoussa-cds commented on serverless/create-record/index.js
> +    let fP = process.env.fileLoca;                  //encrypted env_var
fileLoca looks like a typo?

2021-01-18 16:30 UTC, wmoussa-cds commented on serverless/create-record/index.js
> +    let d = new Date();
d as a variable name?

2021-01-18 16:31 UTC, wmoussa-cds commented on serverless/create-record/index.js
> +// informational for DEV
inline comments as such are not useful, lets keep the code as clean as possible (and readable)

2021-01-18 16:31 UTC, wmoussa-cds commented on serverless/create-record/index.js
> +	var body = JSON.stringify(event);
indent properly

2021-01-18 16:32 UTC, wmoussa-cds commented on serverless/create-record/index.js
> +    let filename = uuid.v1();  // RFC4122 standard uuid Timestamp based generation
i think most initialized variables in the block above should be const

2021-01-18 16:33 UTC, wmoussa-cds commented on serverless/create-record/index.js
> +    if(body.includes("/script" || "< script >" || "alert(" || "SELECT " || "DROP " )){
isn't there a util library we could use instead?

2021-01-18 16:33 UTC, wmoussa-cds commented on serverless/create-record/index.js
> +    // Is this an attack?
instead of an inline comment, use a method

2021-01-18 16:33 UTC, wmoussa-cds commented on serverless/create-record/index.js
> +    else{
bad formatting

2021-01-28 15:40 UTC, CalvinRodo commented
Closing in favour of https://github.com/cds-snc/covid-alert-serverless/pull/2

2021-01-28 15:40 UTC, closed without merging